### ISSUE TITLE
Consider support for asynchronous tasks

### ISSUE THREAD

**Issue by jmandel** [MarcoPolo/servant#4]
For example, allow "servant" (worker) functions to return a channel, and when that happens, park until that channel emits a result. This would allow for worker functions that need to do asynchronous work like fetching and analyzing external web resources.

**Comment by MarcoPolo** [comment]
How is this different to how it works currently?

Looking at this demo: https://github.com/MarcoPolo/servant-demo/blob/master/src/cljs/servant-demo/core.cljs#L44

`(servant/servant-thread servant-channel servant/standard-message some-random-fn 5 6)`

Is a call to a servant function given a channel of available webworkers. It returns a channel that parks until it has a result

**Comment by jmandel** [comment]
I wish I had documented my suggestion better when I had the idea in 2014.

At this point I can't remember what I needed well enough to tell whether your example fits the bill; but that probably means it's safe to close this issue :-)

**Comment by MarcoPolo** [comment]
Thanks :)

**Comment by jmandel** [comment]
Sure -- and FWIW I did use the library successfully in https://github.com/jmandel/mnemonics

**Comment by MarcoPolo** [comment]
Really cool!
